---
- hosts: webserver
  tasks:
  - name: Install frontend base packages
    sudo: yes
    apt: name={{item}} update_cache=yes state=present
    with_items: 
      - git
      - apache2
      - libapache2-mod-php5
